### ISSUE TITLE
$secondarytext not rendered in frontend.css

### ISSUE THREAD

**Issue by bhalpern** [Automattic/WP-Job-Manager#548]
In v.1.23.9 (current version) of the WP-Job-Manager plugin, the following entry begins on line 61 of `wp-job-manager/assets/css/frontend.css`. (WordPress v.4.2.2)

```css
.job-manager-error, .job-manager-info, .job-manager-message {
    padding: 1em 2em 1em 3.5em !important;
    margin: 0 0 2em !important;
    position: relative;
    background-color: #fff;
    color: $secondarytext;
    border-top: 3px solid #999;
    list-style: none outside !important;
    width: auto;
    zoom: 1;
    box-shadow: 0 1px 1px rgba(0, 0, 0, .2)
}
```

The `$` char throws a CSS error, and presumably `$secondarytext` is a variable not being properly rendered by a CSS preprocessor anyway (so we're not getting to see your beautiful selection!). Please advise, or address on next release. It'd be great if you could tell me the color to manually patch this line with in the meantime. Thanks!
