### ISSUE TITLE
RTL styling issues

### ISSUE THREAD

**Issue by wesamly** [Automattic/WP-Job-Manager#652]
Hello,
There is an issue with an RTL website. the text not aligned correctly from Right to Left.
I have attached a screenshot for the Job Listing page, but there is an issue in the Job Details page as well.

What is the best way to add/fix RTL styles?

![screen shot 2016-04-11 at 11 18 55 am](https://cloud.githubusercontent.com/assets/389138/14422551/ad7105c2-ffd7-11e5-8f5c-1d588956e6f2.png)

**Comment by mikejolley** [comment]
There should be an RTL class added to the body so these can be targeted?

**Comment by wesamly** [comment]
I used custom css plugin to add styles to fix the reported issue. Code added below, I believe it still needs some tuning. 

```css
.rp4wp-related-job_listing>ul li.job_listing a img.company_logo, .rp4wp-related-job_listing>ul li.no_job_listings_found a img.company_logo, ul.job_listings li.job_listing a img.company_logo, ul.job_listings li.no_job_listings_found a img.company_logo {
	right: 1em;
	left:0;
    float: right;
    margin-right: 0;
    margin-left: 1em;
}
.rp4wp-related-job_listing>ul li.job_listing a div.position, .rp4wp-related-job_listing>ul li.no_job_listings_found a div.position, ul.job_listings li.job_listing a div.position, ul.job_listings li.no_job_listings_found a div.position {
	float: right;
    padding: 0 42px 0 0 ;
}
.rp4wp-related-job_listing>ul li.job_listing a .meta, .rp4wp-related-job_listing>ul li.no_job_listings_found a .meta, ul.job_listings li.job_listing a .meta, ul.job_listings li.no_job_listings_found a .meta {
	float: left;
    text-align: left;
    padding: 0 1em 0 0 ;
}
.rp4wp-related-job_listing>ul li.job_listing a div.location, .rp4wp-related-job_listing>ul li.no_job_listings_found a div.location, ul.job_listings li.job_listing a div.location, ul.job_listings li.no_job_listings_found a div.location {
	float: right;
    text-align: right;
    width: 25%;
    padding: 0 1em 0 0 ;
}
ul.job_listings .job-manager-applications-applied-notice {
    float: left;
}
.job_filters .job_types li {
   
    float: right;
    border-right: none;
    border-left: 1px solid #eee;
}
.single_job_listing .company img {
    left: 0;
    right: 1em;
    float: right;
}

.single_job_listing .company .name {
    margin: 0 3em 0 0 ;
    padding: 0 1em 0 0 ;
}
```
